yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index,
         name='index'
         ),
    path('profile/<str:username>/',
         views.profile,
         name='profile'
         ),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_posts'
         ),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'
         ),
    path('create/',
         views.post_create,
         name='post_create'
         ),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'
         ),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
    path('follow/',
         views.follow_index,
         name='follow_index'
         ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/',
         admin.site.urls
         ),
    path('auth/',
         include('users.urls',
                 namespace='users')
         ),
    path('auth/',
         include('django.contrib.auth.urls')
         ),
    path('',
         include('posts.urls',
                 namespace='posts')
         ),
    path('about/',
         include('about.urls',
                 namespace='about')
         ),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        blank=True, null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        text = self.text
        if len(text) > 15:
            text = text[:15]
        return text


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Короткая ссылка группы')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата публикации')

    class Meta:
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь подписчик',
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь автор',
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст', 'group': 'Группа', 'image': 'Картинки'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Group, Post, User, Follow


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, settings.COUNT_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')
    paginator = Paginator(posts, settings.COUNT_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.order_by('-pub_date').all()
    paginator = Paginator(post_list, settings.COUNT_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=user,
        ).exists()
    else:
        following = None
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    user_post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = user_post.comments.all()
    context = {
        'form': form,
        'post': user_post,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    context = {
        'groups': groups,
        'form': form,
        'is_edit': False
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    groups = Group.objects.all()
    context = {
        'groups': groups,
        'form': form,
        'post': post,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = (Post.objects.
                 filter(author__following__user=request.user).
                 order_by('-pub_date'))
    paginator = Paginator(post_list, settings.COUNT_PAGES)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # если что-то не так, то можно еще серым натыкать
    # с серыми самостоятельно поработаю, спасибо за труд!
    followed_author = get_object_or_404(User, username=username)
    # if user == author
    if followed_author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=followed_author
        )

    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    followed_author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=followed_author).delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% block title %}
{% if is_edit %}
	Редактировать Запись
{% else %}
	Добавить запись
{% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header"> 
              Новый пост             
              </div>      
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}             
              </div>
              <div class="card-body">      
                <form method="post" action "posts/create_post.html" enctype="multipart/form-data">     
                  {% csrf_token %}            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Выберите группу                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>--------</option>
                      {% for group in groups %}
                        <option value={{ group.id }}>{{ group.title }}</option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
				          <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                  </div>
                  <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Избранные авторы
{% endblock %}
{% block content %}
<div class="container py-5">        
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {{ post.text|linebreaksbr }}
      </p>
		  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
			<img class="card-img my-2" src="{{ im.url }}">
		  {% endthumbnail %}
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </article>  
		{% if post.group %}	
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
		{% endif %}
		{% if not forloop.last %}
        <hr>
		{% endif %}
  {% endfor %}
{% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Записи сообщества: {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title|linebreaksbr }}</h1>
	<p>{{ group.description }}</p>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text|linebreaksbr }}</p>
		{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
			<img class="card-img my-2" src="{{ im.url }}">
		{% endthumbnail %}
    </article>   
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Последние обновления на сайте
{% endblock %}	
{% block content %}
	<div class="container py-5">        
    {% load cache %}
    {% cache 20 index_page page_obj.number %}
    {% include 'posts/includes/switcher.html' %}
		{% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text|linebreaksbr }}
          </p>
		  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
			<img class="card-img my-2" src="{{ im.url }}">
		  {% endthumbnail %}
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        </article>  
		{% if post.group %}	
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
		{% endif %}
		{% if not forloop.last %}
        <hr>
		{% endif %}
		{% endfor %}
    {% endcache %}
		{% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Пост {{ text }}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
              <li class="list-group-item">
              {% endif %}
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text|linebreaksbr }}
          </p>
		  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
			<img class="card-img my-2" src="{{ im.url }}">
		  {% endthumbnail %}
          {% if post.author == user %}
		    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
             редактировать запись
        </a> 
          {% endif %}
        {% include 'posts/includes/comment.html' %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{author}}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{author}} </h1>
    <h3>Всего постов: {{author.posts.count}} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
  </div>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
      {{ post.text|linebreaksbr }}
      </p>
		{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
			<img class="card-img my-2" src="{{ im.url }}">
		{% endthumbnail %}
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
      {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% if not forloop.last %}
	    <hr>
	    {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}